const TransactionTypes = {
    LOOKUP: 'LOOKUP',
    UPDATE_SEARCH: 'UPDATE_SEARCH',
    SEARCH_TRANSACTIONS_SUCCESS: 'SEARCH_TRANSACTIONS_SUCCESS',
    SEARCH_TRANSACTIONS_LOADING: 'SEARCH_TRANSACTIONS_LOADING',
    SEARCH_TRANSACTIONS_FAILURE: 'SEARCH_TRANSACTIONS_FAILURE'
};

export default TransactionTypes;
